export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USERS_GET_REQUEST = "USERS_GET_REQUEST";
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS";
export const USERS_GET_FAIL = "USERS_GET_FAIL";

export const PLACE_CREATE_REQUEST = "PLACE_CREATE_REQUEST";
export const PLACE_CREATE_SUCCESS = "PLACE_CREATE_SUCCESS";
export const PLACE_CREATE_FAIL = "PLACE_CREATE_FAIL";

export const PLACES_BY_USER_GET_REQUEST = "PLACES_BY_USER_GET_REQUEST";
export const PLACES_BY_USER_GET_SUCCESS = "PLACES_BY_USER_GET_SUCCESS";
export const PLACES_BY_USER_GET_FAIL = "PLACES_BY_USER_GET_FAIL";
